Repository mantidproject/reports, pull requests merged in 2022-03, with the labels that each got.

#43 Swap volumes for mounts
  .gitignore
  bin/boot.sh
  bin/shutdown.sh
  blank.env
  docker-compose.yml
  web/requirements.txt
Labels: enhancement

#54 Create .gitattributes file
  .gitattributes
Labels: bug

#53 Updated Python version to 3.10
  web/Dockerfile
Labels: dependencies
